[server]
headless = true
port = 8501
enableCORS = false

[theme]
primaryColor = "#2980b9"
backgroundColor = "#ffffff"
secondaryBackgroundColor = "#f0f2f6"
textColor = "#262730"
font = "sans serif"

[browser]
gatherUsageStats = false
